# ======================== [ BankJago - config.yml ] =========================

# Jenis database: sqlite (default) atau mysql
database:
  type: sqlite
  mysql:
    host: localhost
    port: 3306
    database: bankjago
    user: root
    pass: ""

# === REGISTER ===
register_fee: 50000       # Biaya daftar bank (Rp)
register_start: 25000     # Saldo awal saat berhasil daftar (Rp)
register_capacity: 16     # Kapasitas awal storage (slot)

# === KAPASITAS & UPGRADE ===
upgrade_fee: 20000        # Biaya per upgrade kapasitas (Rp)
max_capacity: 54          # Kapasitas maksimum (slot)

# === TRANSFER & ADMIN ===
transfer-fees:
  under-100000: 1000           # Fee untuk transfer nominal < 100.000
  under-1000000: 2500          # Fee untuk transfer nominal < 1.000.000
  under-10000000: 10000        # Fee untuk transfer nominal < 10.000.000
  under-100000000: 100000      # Fee untuk transfer nominal < 100.000.000

  info-lore:
    - "ยง7Kurang dari Rp100.000 = Rp1.000"
    - "ยง7Kurang dari Rp1.000.000 = Rp2.500"
    - "ยง7Kurang dari Rp10.000.000 = Rp10.000"
    - "ยง7Kurang dari Rp100.000.000 = Rp100.000"

# === SALARY/Gaji Langit ===
salary_interval: 420      # Interval pemberian gaji langit (detik, default 7 menit)
salary_player: 2000       # Gaji langit default player (Rp)
salary_vip: 5000          # Gaji langit VIP (Rp)
salary_vvip: 10000        # Gaji langit VVIP (Rp)

# === LAIN-LAIN ===
lang: id                  # Bahasa
debug: false              # Tampilkan debug log di console?
